services:
  pg-db:
    image: postgres:15
    restart: always
    env_file: ../backend/.env.development
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
volumes:
  pgdata:
networks:
  my-network:
    driver: bridge
