export class StatusCodeEnum{
  public static readonly OK = 200;
  public static readonly CREATED = 201;
  public static readonly ACCEPTED = 202;
  public static readonly NO_CONTENT = 204;
  public static readonly NOT_FOUND = 404;
  public static readonly CONFLICT = 409;
  public static readonly VALIDATION = 422;
  public static readonly UNAUTHORIZED = 401;
  public static readonly FORBIDDEN = 403;
  public static readonly INTERNAL_SERVER_ERROR = 500;
  public static readonly BAD_REQUEST = 400;
  public static readonly SERVICE_UNAVAILABLE = 503;
  public static readonly GATEWAY_TIMEOUT = 504;
  public static readonly TOO_MANY_REQUESTS = 429;
  public static readonly UNPROCESSABLE_ENTITY = 422;
}

export enum ErrorCode {
  INVALID_INPUT = "INVALID_INPUT",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  POSTGRES_ERROR = "POSTGRES_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  RESTRICTED_ACCESS = "RESTRICTED_ACCESS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  CONVERSATION_ALREADY_EXISTS = "CONVERSATION_ALREADY_EXISTS",
  CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND",
  MINIMUM_USERS_NOT_MET = "MINIMUM_USERS_NOT_MET",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}

export enum POSTGRES_ERROR_CODE {
  UNIQUE_VIOLATION = "23505",
  NOT_NULL_VIOLATION = "23502",
  FOREIGN_KEY_VIOLATION = "23503",
  CHECK_VIOLATION = "23514",
  STRING_DATA_RIGHT_TRUNCATION = "22001",
  SYNTAX_ERROR = "42601",
}
